dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests

before_script:
  - export FLASK_APP=politicer
  - export FLASK_DEBUG=1
  - export FLASK_ENV=development

script:
  - python -m pytest 

after_success:
  - coveralls 
  - codeclimate -test-reporter